### ISSUE TITLE
Share a page

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-html-discovery#13]
"As a web user when viewing a Web page, I want to know the ActivityPub equivalent object for that page, so I can share it with an Announce activity."

**Comment by benpate** [comment]
I believe [FEP-3b86](http://w3id.org/fep/3b86) is a good solution to this use case.  To avoid spamming a huge comment on several issues, I added #15 as its own discussion.

**Comment by mediaformat** [comment]
A number of implementations are already using the following meta tag.
`<link rel="alternate" type="application/activity+json" href="https://mediaformat.org/notes/922/">`

Is this issue for something more "on page"?

**Comment by nightpool** [comment]
@mediaformat this issue is a user story which the `link rel` tag (among other solutions) might address.
