### ISSUE TITLE
Document fediverse:creator OpenGraph tag

### ISSUE THREAD

**Issue by AaronNGray** [swicg/activitypub-html-discovery#16]
`<meta name="fediverse:creator" content="username@domain" />`

https://github.com/mastodon/mastodon/pull/30398

https://github.com/mastodon/mastodon/pull/30398#issuecomment-2126193166

**Comment by nightpool** [comment]
I think this repo was basically designed as an alternative to
fediverse:creator, so that kind of defeats the purpose?

**Comment by AaronNGray** [comment]
> I think this repo was basically designed as an alternative to fediverse:creator, so that kind of defeats the purpose?
> […](#)

I just posted this up as an issue for awareness and completeness :) I don't know if we should include it in the spec but it might be an idea to have a wider SWICG document that includes Mastodon based extensions too both for ActivityPub and for the Web.

**Comment by evanp** [comment]
> I think this repo was basically designed as an alternative to fediverse:creator, so that kind of defeats the purpose?

No, I don't think that's true. Discovering the author of an object is only part of discovery.
