### ISSUE TITLE
Follow a link without leaving my ActivityPub API client

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-html-discovery#20]
"As an ActivityPub API client user, when I'm reading some HTML content of an ActivityPub object and I click a link, I want to pull the linked ActivityPub object directly into my client, so I don't have to launch an external browser, and so I can interact with it directly."

Extended example: the user is looking at this object in their ActivityPub API client:

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://social.example/note/1",
  "type": "Note",
  "content": "<p>Check out this link: <a href='https://other.example/blog/page/7'>A blog page</a>"
}
```

When the user clicks on "A blog page", the typical experience is to pop open a browser window and show the page. It may have affordances to interact (comment, like, share, subscribe) but the user will probably need to authenticate to do so.

But what if that page has an ActivityPub representation, like this:

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://api.other.example/pages/iWKsEe4xGCSbCch24J9dH",
  "type": "Article",
  "content": "This is an ActivityPub representation of the blog page.",
  "url": "https://other.example/blog/page/7"
}
```

Pulling the AP version into the API client means that the user can interact with it directly -- comment, like, share, etc. right in their existing API client. The `proxyUrl` in AP makes pulling it easy, but the client needs to know that https://other.example/blog/page/7 has an AP representation and find its location. Discovery helps us with that.

**Comment by evanp** [comment]
> https://w3id.org/fep/e232 was intended to solve this. Just `tag` your link as a `Link` with specifically the activitystreams `mediaType`

It doesn't work if the linked object is not an ActivityPub object.

**Comment by evanp** [comment]
> We want to solve this on Mastodon, and are considering fep-e232, but we are seeing some issues with this FEP. We plan to write down the details when we get to it, but this is definitely on our radar, and something we want to improve.
> 
> There have been several PRs attempting to fix this without AP changes, but they are workarounds at best. See [mastodon/mastodon#26917](https://github.com/mastodon/mastodon/pull/26917) and [mastodon/mastodon#31101](https://github.com/mastodon/mastodon/pull/31101)

Great, let's get it working!

**Comment by trwnh** [comment]
> It doesn't work if the linked object is not an ActivityPub object.

I'm confused, isn't this user story specifically about identifying and pulling in ActivityPub objects?
