### ISSUE TITLE
4.3.2 and 4.3.2.1 -- `fediverse:creator` is not a `property`, it is the `name` of a `<meta>` tag

### ISSUE THREAD

**Issue by trwnh** [swicg/activitypub-html-discovery#32]
## 4.3.2

https://swicg.github.io/activitypub-html-discovery/#opengraph-protocol

> Another option is the `fediverse:creator` <mark>property</mark>, [developed by Mastodon](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/). This <mark>property</mark> is used to identify the creator of a document. Its value is the Webfinger ID of the creator, prefixed with an `@` character, not an `acct:` URL. The consumer can use the Webfinger protocol to find the ActivityPub object corresponding to the creator.

"property" should be "`<meta>` tag" or possibly "tag" or "metadata tag"

### 4.3.2.1

https://swicg.github.io/activitypub-html-discovery/#example-3

> `<meta property="fediverse:creator" content="@person-22@ap.example" />`

`property=` should be `name=`

**Comment by evanp** [comment]
They're called properties in [OpenGraph protocol](https://ogp.me/) parlance and OGP uses `property` as the attribute. I added a parenthetical note to remind the reader of this.

**Comment by trwnh** [comment]
@evanp the problem is that `fediverse:creator` is NOT opengraph.

the parenthetical is incorrect. `property` IS a standard property, it comes from RDFa.

`fediverse:creator` may look like a namespace prefix, but it is not. it is more like `twitter:creator` which is just a standard `<meta>` tag that doesn't use RDFa. this is why both `twitter:creator` and `fediverse:creator` use `name=` instead of `property=`.
