### ISSUE TITLE
4.4.1: include example of rel=author with type=activitystreams?

### ISSUE THREAD

**Issue by trwnh** [swicg/activitypub-html-discovery#33]
https://swicg.github.io/activitypub-html-discovery/#example-4

```html
<link
      rel="author"
      type="text/html"
      href="https://html.example/profiles/person-22.html" />
```

maybe a similar example such as this?

```html
<link
      rel="author"
      type="application/activity+json"
      href="https://html.example/profiles/person-22.jsonld" />
```

note that we should probably advise not to mix the two approaches

**Comment by evanp** [comment]
Discovery of the AP link directly is covered in an earlier example.

https://swicg.github.io/activitypub-html-discovery/#example-2

The example you're linking is about taking an indirect path from resource HTML to author ActivityPub through the author profile HTML.

**Comment by trwnh** [comment]
ok, this is confusing because Section 4 is "HTML to author ActivityPub", and Section 4.4 is "Discovering author HTML", which doesn't fit hierarchically under Section 4.

i think generally the structure of each section is also confusing because it lacks parallelism; "Discover equivalent object" is placed at the same level as "URL as input" or "Document as input". i think that differentiating by input method should probably happen at a different (higher?) level, before considering what it is you're actually looking for. which is to say that the hierarchy should be a lot different. i think i'll file a new issue for that, but for this example/case, i would expect both examples to be in the same section or very nearby, dealing with:

- http(s) URI
  - -> preflight check (HTTP HEAD)
    - -> HTTP Link header
      - rel=author type=activitystreams
      - rel=author type=html or unknown type
  - -> conneg (HTTP GET with Accept header) if preflight fails
    - -> AS2 document (take `attributedTo`)
    - -> HTML document (go to "forward discovery" section)

this requires a lot more thought because it has significant implications for the structure of the report as a whole

**Comment by evanp** [comment]
> ok, this is confusing because Section 4 is "HTML to author ActivityPub", and Section 4.4 is "Discovering author HTML", which doesn't fit hierarchically under Section 4.

It does, actually. Here's the introductory text for the "discovering author HTML" section:

> 4.4 Discovering author HTML
> Another option for author discovery is to discover the HTML profile page for the author of the resource, and then discover the equivalent ActivityPub object for the HTML profile page.

So, "Discovering author HTML" is a technique for discovering the author ActivityPub ID. Discovering the author HTML is a step along the way. 

There's a note about this in the introduction, too:

> There are a few paths for author discovery:
> 
> resource HTML → resource ActivityPub → author ActivityPub
> resource HTML → author HTML → author ActivityPub
> resource HTML → author ActivityPub

I'll see if I could make it clearer, but this section very much belongs under "HTML to Author ActivityPub".
