### ISSUE TITLE
Document use of Webfinger for discovery

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-html-discovery#6]

**Comment by benpate** [comment]
I want to add two "thumbs ups" to this one because it's such a huge part of interacting on the Fediverse. But I can't, so I'm just writing this comment as my +2

**Comment by nightpool** [comment]
Strong -1 against embedding webfinger any further in any new roles for "HTML discovery", we already have a separate document explaining webfinger that should serve to document the existing use-cases for it and discourse adding new use-cases for it, it's just too complex of a spec and has too many unnecessary, un-ActivityPub-like restrictions. I don't think it's a good fit for this use-case.

**Comment by evanp** [comment]
@nightpool I think it's one of our only options for doing discovery for a binary data file like JPG or MP4. (Other options: Link: header, LRDD, ...)

It's also an endpoint that almost every AP server implements for looking up actors, so it's going to be an easy one to augment with document/file lookup.
